const account = {
  LOG_OUT: 'LOG_OUT',
  SET_USER_DATA: 'SET_USER_DATA',
  SET_VERIFIED: 'SET_VERIFIED',
};

const general = {
  SET_ERROR: 'SET_ERROR',
  SET_MODAL_CONTENT: 'SET_MODAL_CONTENT',
  SET_SIDEBAR_OPEN: 'SET_SIDEBAR_OPEN',
};

const chats = {
  // === Actual Chats ===
  SET_CHATS: 'SET_CHATS',
  ADD_CHAT: 'ADD_CHAT',
  SOMEONE_LEFT_CHAT: 'SOMEONE_LEFT_CHAT',
  SOMEONE_INVITED_TO_CHAT: 'SOMEONE_INVITED_TO_CHAT',
  EDIT_CHAT: 'EDIT_CHAT',

  // === Messages ===
  SET_MESSAGES: 'SET_MESSAGES',
  ADD_MESSAGE: 'ADD_MESSAGE',
  MARK_READ: 'MARK_READ',
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  EDIT_MESSAGE: 'EDIT_MESSAGE',
};

const search = {
  SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
  SET_SEARCH_IS_LOADING: 'SET_SEARCH_IS_LOADING',
};

export {
  account,
  general,
  chats,
  search
};