const account = {
  LOG_OUT: 'LOG_OUT',
  SET_USER_DATA: 'SET_USER_DATA',
  SET_VERIFIED: 'SET_VERIFIED',
};

const general = {
  SET_ERROR: 'SET_ERROR',
  PUSH_MODAL: 'PUSH_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  SET_SIDEBAR_OPEN: 'SET_SIDEBAR_OPEN',
};

const chats = {
  // === Actual Chats ===
  SET_CHATS: 'SET_CHATS',
  ADD_CHAT: 'ADD_CHAT',
  SOMEONE_LEFT_CHAT: 'SOMEONE_LEFT_CHAT',
  SOMEONE_INVITED_TO_CHAT: 'SOMEONE_INVITED_TO_CHAT',
  EDIT_CHAT: 'EDIT_CHAT',

  // === Messages ===
  SET_MESSAGES: 'SET_MESSAGES',
  ADD_MESSAGE: 'ADD_MESSAGE',
  MARK_READ: 'MARK_READ',
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  EDIT_MESSAGE: 'EDIT_MESSAGE',

  // === Chat Window ===
  CLICK_MESSAGE: 'CLICK_MESSAGE',
  CLEAR_SELECTED_MESSAGES: 'CLEAR_SELECTED_MESSAGES',
  SET_MESSAGES_TO_MENTION: 'SET_MESSAGES_TO_MENTION',
  SET_IS_EDITING: 'SET_IS_EDITING',
  SET_VALUES_BEFORE_EDITING: 'SET_VALUES_BEFORE_EDITING',
  SET_EDITED_MSG_INITIAL: 'SET_EDITED_MSG_INITIAL',
  SET_SCROLL_TO_MESSAGE: 'SET_SCROLL_TO_MESSAGE',
  SET_DATA_TO_REBASE: 'SET_DATA_TO_REBASE',
};

export {
  account,
  general,
  chats
};